### ISSUE TITLE
Pretrained Weights?

### ISSUE THREAD

**Issue by James-R-Han** [HarryShomer/LPFormer#5]
Hi Harry!

First off, love this work! I was wondering if you have any pretrained weights that could please release. Our team would like to see how LPFormer performs off of our Ouster Lidar in indoor settings.

Best,

James

**Comment by HarryShomer** [comment]
Thanks!

I currently don't have the pretrained weights saved.

I should note, that LPFormer is not meant to be generalized across datasets. It is meant to be used in a supervised fashion only. As such, it is unlikely that it would be able to generalize well to other datasets (this is especially true for very different tasks like Lidar). Also, the input dimension of the trained model depends on the dimension of the input features, which is generally different for different datasets.

I'd therefore recommend training it from scratch for your specific task.
